<?php
/**
* @file
* A block module that displays instagram images.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/

/**
* Implements hook_block_info().
*/
function instagram_block_block_info() {
  $blocks['instagram_block'] = array(
    'info' => t('Instagram Block'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*
* Prepares the contents of the block.
*/
function instagram_block_block_view($delta = '') {
      
  switch($delta){
    case 'instagram_block':
      $my_settings = array(
      'number_of_instagrams' => variable_get('number_of_instagrams'),
      'instagram_tag' => variable_get('instagram_tag'),
      'resolution' => variable_get('resolution'),
      'client_id' => variable_get('client_id')
      );
      drupal_add_js(array('instagram_block' => $my_settings), 'setting');      
      $block['subject'] = t('Instagrams');
      $block['content'] = '<div class="instagram-feed"></div><div class="clearfix"></div>';
      return $block;      
  } 
}

/**
* Implements hook_menu().
*/
function instagram_block_menu() {
  $items = array();

  $items['admin/config/content/instagram_block'] = array(
    'title' => 'Konfigurera instagramvisning',
    'description' => 'Ändrar inställningar för instagrambilder',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('instagram_block_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
* Page callback: Current posts settings
*
* @see instagram_block_menu()
*/

function instagram_block_form($form, &$form_state) {
  $form['number_of_instagrams'] = array(
    '#type' => 'textfield',
    '#title' => t('Antal bilder att visa'),
    '#default_value' => variable_get('number_of_instagrams'),
    '#size' => 2,
    '#maxlength' => 2,   
    '#required' => TRUE,
  );

  $form['instagram_tag'] = array(
    '#type' => 'textfield',
    '#title' => t('#Tag'),
    '#default_value' => variable_get('instagram_tag'),
    '#size' => 50,
    '#maxlength' => 50,    
    '#required' => TRUE,
  );

  $form['client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Client Id'),
    '#default_value' => variable_get('client_id'),
    '#size' => 50,
    '#maxlength' => 50,    
    '#required' => TRUE,
    '#description' => t('Client Id hämtas från Instagram')
  );

  $form['resolution'] = array(
    '#type' => 'select',
    '#title' => t('Storlek'),
    '#default_value' => variable_get('resolution'),
    '#options' => array(

      'thumbnail' => t('Thumbnail'), 
      'low_resolution' => t('Low Resolution'), 
      'standard_resolution' => t('Standard Resolution'),
      ),    
    '#required' => TRUE,
  );
  return system_settings_form($form);
}
